apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: build-suite-test-component-image-url-shby
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: build-suite-test-component-image-url-shby
    app.kubernetes.io/part-of: test-app-hnoc
  name: build-suite-test-component-image-url-shby
  namespace: e2e-test-rkaw
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: build-suite-test-component-image-url-shby
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: build-suite-test-component-image-url-shby
    spec:
      containers:
      - image: quay.io/psturc/test-images-protected
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources: {}
status: {}
