apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: build-suite-test-component-image-url-vtzp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: build-suite-test-component-image-url-vtzp
    app.kubernetes.io/part-of: test-app-hnoc
  name: build-suite-test-component-image-url-vtzp
  namespace: e2e-test-rkaw
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: build-suite-test-component-image-url-vtzp
status:
  loadBalancer: {}
